# Generated by Django 4.2.1 on 2023-09-26 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.TextField()),
                ('ContactFullName', models.TextField()),
                ('BillAddress', models.TextField()),
                ('City', models.TextField()),
                ('PostalCode', models.TextField()),
                ('Country', models.TextField()),
                ('RecieverJobPosition', models.TextField()),
                ('PhoneNumber', models.TextField()),
                ('Fax', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('GoodName', models.TextField()),
                ('Producer', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('PostingDate', models.TextField()),
                ('OrderNUM', models.TextField()),
                ('ReceiverName', models.TextField()),
                ('ReceiverAddress', models.TextField()),
                ('ReceiverPostalCode', models.TextField()),
                ('ReceiverPhoneNumber', models.TextField()),
                ('ExecutionDate', models.TextField()),
                ('DeliveryPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('WorkerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Surname', models.TextField()),
                ('Position', models.TextField()),
                ('InternalPhoneNumber', models.TextField()),
                ('WorkPhoneNumber', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierOrganizationID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierOrganizationName', models.TextField(unique=True)),
                ('Country', models.TextField()),
                ('City', models.TextField()),
                ('PostalCode', models.TextField()),
                ('Adress', models.TextField()),
                ('PhoneNumber', models.TextField(unique=True)),
                ('Fax', models.TextField(unique=True)),
                ('StandartPayMethod', models.TextField()),
                ('StandartBankAccount', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('PayID', models.AutoField(primary_key=True, serialize=False)),
                ('PayAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PayDate', models.TextField()),
                ('PayMethod', models.TextField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='StaffWorkerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staff'),
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('ID_of_ordered', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.goods')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orders')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='SopplierCompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.suppliers', to_field='SupplierOrganizationName'),
        ),
    ]
